### PR TITLE
Support iOS15

### PR DESCRIPTION
**Pull request by batschz**
### Issue Link :link:
The extension for TextField is causing an infinity loop in iOS15

### Goals :soccer:
Make it work for iOS 15

### Implementation Details :construction:
- Removing the extension and updating the tests

### CODE REVIEW

**Comment by dks333** [comment]
Nice work! I have already done editing the same thing in my project to work with iOS 15😂

**Comment by CSolanaM** [comment]
Thank you for your PR!

I understand the need of removing that extension if you don't need it but, after reviewing your PR and also taking a look in the latest Xcode beta, it looks like is just a function signature issue.

For some reason, now, the inference believes it's calling itself despite of the optional. The behavior was the opposite back then.

If you just try to change the signature (any label, for example), the `TextField` extension could be kept, and also the test, so it actually uses the code (right now you're testing Apple's `TextField` initializer).

**Comment by batschz** [comment]
Thanks @CSolanaM for your suggestion - I hope I got it right what you meant

**Review by CSolanaM — APPROVED** [review]
👍🏻 + Thank you very much!

**Pull request merged**
